print('BIO DATA')
name=input('enter your name:')
age=int(input('enter your age:'))
father=input('enter your father name:')
mother=input('enter your mother name:')
ph=int(input('enter your mobile number:'))
print(name)
print(age)
print(father)
print(mother)
print(ph)
n=int(input('enter a number'))
m=int(input('enter another number'))
c=n*m
print(c)
